SanaAssessment.Web/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SanaAssessment.Data;
using SanaAssessment.Data.Entities;
using SanaAssessment.Web.Helper;

namespace SanaAssessment.Web.Controllers
{
    public class CustomersController : Controller
    {
        private readonly SanaContext _context;
        private readonly SanaContext _contextMemory;

        public CustomersController(SanaContext context)
        {
            _context = context;
            var options = new DbContextOptionsBuilder<SanaContext>()
                         .UseInMemoryDatabase("SanaInMemory")
                         .Options;
            _contextMemory = new SanaContext(options);
        }

        private SanaContext dbcontext
        {
            get
            {
                var currentStorage = HttpContext.Session.Get<string>(SessionExtensions.SessionKeyStorageType);
                if (currentStorage == "SQL")
                {
                    return _context;
                }
                else
                {
                    return _contextMemory;
                }
            }
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await dbcontext.Customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await dbcontext.Customers
                .SingleOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdentificationNumber,FirtsName,MiddleName,LastName")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                dbcontext.Add(customer);
                await dbcontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await dbcontext.Customers.SingleOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdentificationNumber,FirtsName,MiddleName,LastName")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dbcontext.Update(customer);
                    await dbcontext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await dbcontext.Customers
                .SingleOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await dbcontext.Customers.SingleOrDefaultAsync(m => m.Id == id);
            dbcontext.Customers.Remove(customer);
            await dbcontext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return dbcontext.Customers.Any(e => e.Id == id);
        }
    }
}

SanaAssessment.Web/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SanaAssessment.Data;
using SanaAssessment.Data.Entities;
using SanaAssessment.Web.Models;
using SanaAssessment.Web.Helper;

namespace SanaAssessment.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly SanaContext _context;
        private readonly SanaContext _contextMemory;

        public ProductsController(SanaContext context)
        {
            _context = context;
            var options = new DbContextOptionsBuilder<SanaContext>()
                         .UseInMemoryDatabase("SanaInMemory")
                         .Options;
            _contextMemory = new SanaContext(options);
        }

        private SanaContext dbcontext
        {
            get
            {
                var currentStorage = HttpContext.Session.Get<string>(SessionExtensions.SessionKeyStorageType);
                if (currentStorage == "SQL")
                {
                    return _context;
                }
                else
                {
                    return _contextMemory;
                }
            }
        }
        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await dbcontext.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await dbcontext.Products.Include(p => p.ProductCategories).SingleOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            LoadCategoriesInfo(product, true);
            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            LoadCategoriesInfo(null);
            return View();
        }

        private void LoadCategoriesInfo(Product product, bool assignedOnly = false)
        {
            var allCategories = dbcontext.Categories;
            var viewModel = new List<ProductsCategoriesViewModel>();
            var productCategories = new List<short>();
            if (product != null)
            {
                productCategories = product.ProductCategories.Select(pc => pc.CategoryId).ToList();
            }
            viewModel = allCategories.Select(c => new ProductsCategoriesViewModel { CategoryId = c.Id, CategoryDescription = c.Description, Assigned = productCategories.Contains(c.Id) }).ToList();
            if (assignedOnly)
            {
                viewModel = viewModel.Where(v => v.Assigned).ToList();
            }
            ViewData["Categories"] = viewModel;
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SKU,Description,Price")] Product product, List<short> selectedCategories)
        {
            if (ModelState.IsValid)
            {
                dbcontext.Add(product);
                UpdateProductCategories(product, selectedCategories);
                await dbcontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            LoadCategoriesInfo(null);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await dbcontext.Products.Include(p => p.ProductCategories).SingleOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            LoadCategoriesInfo(product);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SKU,Description,Price")] Product product, List<short> selectedCategories)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            var productForUpdate = await dbcontext.Products.Include(p => p.ProductCategories).SingleOrDefaultAsync(m => m.Id == id);
            product.ProductCategories = productForUpdate.ProductCategories;

            if (ModelState.IsValid)
            {
                try
                {                  
                    dbcontext.Update(product);
                    UpdateProductCategories(product, selectedCategories);
                    await dbcontext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            LoadCategoriesInfo(productForUpdate);
            return View(product);
        }

        private void UpdateProductCategories(Product product, List<short> categories)
        {
            if (categories == null)
            {
                product.ProductCategories = new List<ProductCategory>();
                return;
            }
            if (product.ProductCategories == null)
            {
                product.ProductCategories = new List<ProductCategory>();
            }

            var productCategories = product.ProductCategories.Select(pc => pc.CategoryId).ToList();
            var allCategories = dbcontext.Categories;
            foreach (var cat in allCategories)
            {
                if (categories.Contains(cat.Id))
                {
                    if (!productCategories.Contains(cat.Id))
                    {
                        product.ProductCategories.Add(new ProductCategory { CategoryId = cat.Id, ProductId = product.Id });
                    }
                }
                else
                {
                    if (productCategories.Contains(cat.Id))
                    {
                        ProductCategory courseToRemove = product.ProductCategories.FirstOrDefault(p => p.CategoryId == cat.Id);
                        dbcontext.Remove(courseToRemove);
                    }
                }
            }
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await dbcontext.Products
                .SingleOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await dbcontext.Products.SingleOrDefaultAsync(m => m.Id == id);
            dbcontext.Products.Remove(product);
            await dbcontext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return dbcontext.Products.Any(e => e.Id == id);
        }
    }
}

SanaAssessment.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -  Sana Assessment ASP.NET MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sana Assessment</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li><a asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/Microsoft.jQuery.Unobtrusive.Ajax/jquery.unobtrusive-ajax.min.js"></script>
    </environment>
    <div class="container body-content">
        <div>
            @await Component.InvokeAsync("StorageConfiguration")
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Sana Assessment ASP.NET MVC</p>
        </footer>
    </div>

    <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
    
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>